---
title: "PcoA plot"
output: html_document
---

**Loading packages** 
```{r}
library(Rcpp)
library(dada2)
library(phyloseq)
library(ggplot2)
library(Biostrings)
library(microbiome)
library(devtools)
library(BiocGenerics)
library(plyr)
library(tidyverse)
library(dplyr)
library(cowplot)
library(xlsx)
library(readxl)
library(reshape2) 
library(dplyr)
library(ggthemes)
```

**Load data**
```{r}
## Har ikke sat nye taxtable ind, havde problemer med én NA =Match quality
taxtable=read.table("/Volumes/data/MPV/projects/microbiome/Aureome_development/DADA2_pipelines/NuoL1_blast_output/NuoL1_seq74_tax_and_counts_BLAST_detailed copy.csv",header = TRUE,sep = ",")

new_taxtable = data.frame()
for (i in 1:length(taxtable$blast_assignment)) {
  new_taxtable = rbind(new_taxtable,strsplit(taxtable$blast_assignment[i],";")[[1]])
}
colnames(new_taxtable) = c("Species","Clonal_complex","Sequence_Type","Sequence")
rownames(new_taxtable) = taxtable$ASV
new_asvtable= taxtable[,-c(1:4)]
rownames(new_asvtable) = taxtable$ASV
```

**Create new dataset**
```{r}
meta_smed<-read_excel("/Volumes/data/MPV/projects/microbiome/Aureome_development/Lab/Primary samples/Meta_data_from_Sofie.xlsx")
meta_spa<-read_excel("/Volumes/data/MPV/projects/microbiome/Aureome_development/Lab/Primary samples/Samples_Seq74_KBJA.xlsx")

##Samlpe_data, separation based on sampleID
sam_df = data.frame(SampleID = colnames(new_asvtable)) %>% 
  mutate(Type = case_when(grepl("Mock",SampleID) ~ "Mock",
                        grepl("Neg",SampleID) ~ "Neg control",
                        grepl("NEG",SampleID) ~ "Neg control",
                        grepl("_LS",SampleID) ~ "LS skin",
                        grepl("_NLS_",SampleID) ~ "NLS skin",
                        grepl("Nose",SampleID) ~ "Nose",
                         grepl("NOSE",SampleID) ~ "Nose",
                         grepl("nose",SampleID) ~ "Nose",
                          TRUE ~ "Sample"))

sam_df$SampleID_v2<-gsub(pattern="nose",replacement = "Nose",sam_df$SampleID)
sam_df$SampleID_v2<-gsub(pattern="NOSE",replacement = "Nose",sam_df$SampleID_v2)

sam_df<-sam_df %>%
  separate(SampleID_v2,c("SampleID_short","remove"),sep="_n",remove=FALSE) %>%
  select(-remove) %>%
  left_join(meta_smed,by=c("SampleID_short"="sample_id")) %>%
  left_join(meta_spa,by="SampleID_short") %>%
  mutate(replicate=case_when(
    grepl("_n_",SampleID) ~"sample",
    grepl("_n1_",SampleID) ~"sample",
    grepl("_n2_",SampleID) ~"duplicate",
  ))


sam_df<-sam_df %>% mutate(Mock=case_when(
  SampleID_short=="MockE1" ~"Even mock",
  SampleID_short=="MockE2" ~"Even mock",
  SampleID_short=="MockE3" ~"Even mock",
  SampleID_short=="MockE4" ~"Staggered mock",
 ))

sam_df<-sam_df %>% mutate(ADnose_Healthynose=case_when(
  samplesite=="AD_LS" ~"AD_LS",
  samplesite=="AD_NLS" ~"AD_NLS",
  samplesite=="AD_nose" ~"AD_Nose",
  samplesite=="AD_Nose" ~"AD_Nose",
  samplesite=="AD_NOSE" ~"AD_Nose",
  samplesite=="Control_nose" ~"Healthy_Nose",
  Type=="Neg control" ~"Negative control",
  Type=="Mock" ~"Mock"))

rownames(sam_df) = sam_df$SampleID
```

**Create phyloseq, 500 read cutoff**
```{r}
ps<-phyloseq::phyloseq(otu_table(new_asvtable,taxa_are_rows = TRUE),sample_data(sam_df),tax_table(as.matrix(new_taxtable)))
sample_data(ps)$SeqCount<-sample_sums(ps)

ps = prune_samples(sample_sums(ps)>=500, ps)
```

**Relative abundance**
```{r}
relative<-transform_sample_counts(ps,function(x) x/sum(x))
ps_df<-psmelt(relative) %>% arrange(OTU,Sample)
ps_df_rel<-psmelt(relative) %>% arrange(OTU,Sample) %>% mutate(Abundance=Abundance*100)
```

**PCoA of paired samples**
```{r}
#make new column with mutate
library(ggrepel)

df_500 <- as.data.frame(sample_data(ps))

dfP <- df_500 %>% group_by(SampleID_short) %>% mutate(paired = n()) %>% mutate(SampleID2 = SampleID) %>% tibble::column_to_rownames("SampleID2")

sample_data(ps) <- sample_data(dfP)

ps_paired <- subset_samples(ps,  paired==2 & !Type %in% c("Neg control", "Mock"))

#antal par:
length(unique(sample_data(ps_paired)$SampleID_short))

#antal prøver per type
table(sample_data(ps_paired)$ADnose_Healthynose)
```

```{r,fig.height=15,fig.width=15}
ps_paired_hell <- transform_sample_counts(ps_paired, function(x) sqrt(x / sum(x))) #hellinger transform

ps_paired_hell_ord <- ordinate(ps_paired_hell, method = "PCoA", distance = "bray", na.rm=T)

ord_plot <- plot_ordination(ps_paired_hell, ps_paired_hell_ord, type="samples", color="SampleID_short", axes = 1:2)

coul <- c(brewer.pal(12, "Set3"), brewer.pal(12,"Paired"))
coul <- colorRampPalette(coul)(length(unique(sample_data(ps_paired_hell)$SampleID_short)))


set.seed(1)

beta <-ord_plot  + geom_point(size=3) +
  theme(legend.position = "none") +
  facet_wrap(.~ADnose_Healthynose, ncol=2) +
  geom_line(aes(group=SampleID_short)) +
  scale_color_manual(values=coul) + 
  theme(panel.background = element_rect(fill = "white",
                                colour = "white")) + 
  theme(  panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line = element_line(size = 0.5, linetype = "solid",
                                   colour = "black"))
  #geom_text_repel(aes(label=SampleID_short), max.overlaps = Inf, size = 4, force=1) 

#ggsave(beta, device = "png", width = 30, height = 20, units = "cm", file ="/Users/kirstinebjergandersen/Desktop/duplicates_500cutoff.png")

```



